<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LamisaMart.Ordering.Application\LamisaMart.Ordering.Application.csproj" />
    <ProjectReference Include="..\LamisaMart.Ordering.Domain\LamisaMart.Ordering.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\LamisaMart.Shared.Infrastructure\LamisaMart.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
